/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_accueil (void);
GtkWidget* create_authentification (void);
GtkWidget* create_inscription (void);
GtkWidget* create_admin (void);
GtkWidget* create_gestion_agent (void);
GtkWidget* create_ajout_agent (void);
GtkWidget* create_modifier_agent (void);
GtkWidget* create_supprimer_agent (void);
GtkWidget* create_client (void);
GtkWidget* create_agent (void);
GtkWidget* create_gestion_des_prestations (void);
GtkWidget* create_gestion_prestations_voitures (void);
GtkWidget* create_ajout_voiture (void);
GtkWidget* create_supprimer_voiture (void);
GtkWidget* create_modifier_voiture (void);
GtkWidget* create_gestion_evaluation (void);
GtkWidget* create_ajout_evaluation (void);
GtkWidget* create_supprimer_evaluation (void);
GtkWidget* create_modifier_evaluation (void);
GtkWidget* create_gestion_client (void);
GtkWidget* create_ajout_client (void);
GtkWidget* create_supprimer_client (void);
GtkWidget* create_modifier_client (void);
GtkWidget* create_gestion_prestations_vols (void);
GtkWidget* create_ajout_vol (void);
GtkWidget* create_supprimer_vol (void);
GtkWidget* create_modifier_vol (void);
GtkWidget* create_reservation (void);
GtkWidget* create_reservationvol (void);
GtkWidget* create_reservationvoiture (void);
GtkWidget* create_code_promotionnel (void);
GtkWidget* create_visiteur (void);
