/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *accueil;
  GtkWidget *authentification;
  GtkWidget *inscription;
  GtkWidget *admin;
  GtkWidget *gestion_agent;
  GtkWidget *ajout_agent;
  GtkWidget *modifier_agent;
  GtkWidget *supprimer_agent;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  accueil = create_accueil ();
  gtk_widget_show (accueil);
  //authentification = create_authentification ();
  //gtk_widget_show (authentification);
  //inscription = create_inscription ();
  //gtk_widget_show (inscription);
  //admin = create_admin ();
  //gtk_widget_show (admin);
  //gestion_agent = create_gestion_agent ();
  //gtk_widget_show (gestion_agent);
  //ajout_agent = create_ajout_agent ();
  //gtk_widget_show (ajout_agent);
  //modifier_agent = create_modifier_agent ();
  //gtk_widget_show (modifier_agent);
  //supprimer_agent = create_supprimer_agent ();
  //gtk_widget_show (supprimer_agent);
  //client = create_supprimer_client ();
  //gtk_widget_show (client);
  //agent = create_supprimer_agent ();
  //gtk_widget_show (agent);

  gtk_main ();
  return 0;
}

